DLL_QUERY = """
-- MySQL Script generated by MySQL Workbench
-- Thu Mar 23 23:07:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Reviews_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Reviews_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Reviews_DB` DEFAULT CHARACTER SET utf8 ;
USE `Reviews_DB` ;

-- -----------------------------------------------------
-- Table `Reviews_DB`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reviews_DB`.`Product` (
  `IdProduct` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(150) NULL,
  `CategoryId` INT NULL,
  `Price` FLOAT NULL,
  `DiscountPercentage` FLOAT NULL,
  `ImageLink` VARCHAR(100) NULL,
  `ProductoLink` VARCHAR(150) NULL,
  PRIMARY KEY (`IdProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reviews_DB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reviews_DB`.`User` (
  `IdUser` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NULL,
  PRIMARY KEY (`IdUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reviews_DB`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reviews_DB`.`Review` (
  `IdReview` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL,
  `Content` LONGTEXT NULL,
  `Date` DATE NULL,
  `DiscountPercentage` FLOAT NULL,
  `Raiting` FLOAT NULL,
  `ReviewType` INT NULL,
  `Product_IdProduct` INT NOT NULL,
  `User_IdUser` INT NOT NULL,
  PRIMARY KEY (`IdReview`),
  INDEX `fk_Review_Product_idx` (`Product_IdProduct` ASC) VISIBLE,
  INDEX `fk_Review_User1_idx` (`User_IdUser` ASC) VISIBLE,
  CONSTRAINT `fk_Review_Product`
    FOREIGN KEY (`Product_IdProduct`)
    REFERENCES `Reviews_DB`.`Product` (`IdProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_User1`
    FOREIGN KEY (`User_IdUser`)
    REFERENCES `Reviews_DB`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
"""